[tools]
helm = "3.17.3"
kubectl = "1.37.0"
kind = "0.31.0"
yq = "4.45.4"
jq = "1.7.1"
kubeconform = "0.8.0"
lefthook = "2.1.14"

# Tasks for checking support bundle testing CLI
[tasks.check-verification]
description = "Run the same checks as CI"
depends = ["build", "clippy", "format-check", "test"]

[tasks.build]
run = "cargo build --manifest-path=bundle-verification/Cargo.toml"

[tasks.clippy]
run = "cargo clippy --manifest-path=bundle-verification/Cargo.toml"

[tasks.test]
run = "cargo test --manifest-path=bundle-verification/Cargo.toml"

[tasks.format-check]
run = "cargo +nightly fmt --all --manifest-path=bundle-verification/Cargo.toml -- --check"
