name: Test with RTF

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  run_rtf_test_plan:
    name: Run RTF Test Plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: apollographql/release-tooling/rtf-orchestrator-run-known@2a86a497f7ba8a809b4903c63d0ccbb2d539ebc7
        with:
          git_ref: dmallare/create-basic-rtf-test-plan
          test_plan_id: d92be985-ca2a-457c-9fc8-d692256782ae
